app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#RedirctingController
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]